CREATE TABLE product
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name    VARCHAR(255) NOT NULL,

    created_on      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_by     BIGINT,
    modified_on     TIMESTAMP WITHOUT TIME ZONE,

    created_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by      BIGINT,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_by      BIGINT,
    deleted_at      TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE INDEX idx_product_name ON product (product_name);