CREATE TABLE item
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id      BIGINT NOT NULL,
    quantity        BIGINT NOT NULL,

    created_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by      BIGINT,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_by      BIGINT,
    deleted_at      TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE INDEX idx_item_product_id ON item (product_id);